on:
  push:
    paths-ignore:
      - 'README.md'
    branches-ignore:
      - 'main'

env:
  myWebAppName: 'mywebapp'
  myWebAppVersion: '0.1'
  buildEnv: 'dev'

jobs:
  build_test:
    environment: ${{ buildEnv }}
    name: Build and run tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - id: unittest
        name: Unit tests
        working-directory: MyWebApiTest
        run: |
          $unitTestFilePath = "${{ env.RUNNER_TEMP }}\TestResults\unittests.xml"            
          dotnet test --logger "junit;LogFilePath=$unitTestFilePath"

      - name: Publish test \TestResults
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        with:
          files: ${{ env.RUNNER_TEMP }}\TestResults\unittests.xml

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - id: build-mywebapp
        name: Build MyWebApp
        run: |
          .\Deployment\Build.ps1 -appName ${{ env.myWebAppName }} `
            -appVesion ${{ env.myWebAppVersion }} `
            -buildEnv ${{ env.buildEnv }} `
            -buildPath MyWebApi
